git clone git@github.com:ctrlpvim/ctrlp.vim.git ~/.vim/bundle/ctrlp.vim.git
git clone git@github.com:fugue/ludwig-vim.git ~/.vim/bundle/ludwig-vim.git
git clone git@github.com:kylef/apiblueprint-vim.git ~/.vim/bundle/apiblueprint-vim.git
git clone git@github.com:kien/ctrlp-vim.git ~/.vim/bundle/ctrlp-vim.git
git clone git@github.com:fugue/ludwig-vim/ ~/.vim/bundle/ludwig-vim/
git clone git@github.com:vim-syntastic/syntastic/ ~/.vim/bundle/syntastic/
git clone git@github.com:guns/vim-clojure-static/ ~/.vim/bundle/vim-clojure-static/
git clone git@github.com:fatih/vim-go/ ~/.vim/bundle/vim-go/
git clone git@github.com:digitaltoad/vim-pug/ ~/.vim/bundle/vim-pug/
git clone git@github.com:tpope/vim-surround/ ~/.vim/bundle/vim-surround/
